replicaCount: 3

image:
  repository: bitnami/kafka
  tag: 3.1.0-debian-10-r0

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

zookeeper:
  replicaCount: 3

persistence:
  enabled: true
  size: 10Gi
  storageClass: 