replicaCount: 3

image:
  repository: bitnami/kafka
  tag: 3.1.0-debian-10-r0

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"

zookeeper:
  replicaCount: 3

persistence:
  enabled: true
  size: 10Gi
  storageClass: "standard"  # Add your storage class here if you have one
